training_pipeline_config:
  pipeline_name: housing
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 

data_validation_config:
  data_validation_dir: data_validation
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_page_file_name: report.html

data_transformation_config:
  data_transformation_dir : data_transformation
  add_bedroom_per_room: true
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  json_info_file_path: json_train_info.json

  
model_trainer_config:
  model_training_dir: model_training
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model.yaml
  model_info_json_file_name : model_info_json.json
  cluster_dir : trained_cluster
  cluster_file_name : cluster.pkl


model_evaluation_config:
  model_evaluation_dir: model_evaluaiton
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_pusher_dir: model_pusher
  model_export_dir: saved_models